name: Test actions check
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: [self-hosted, IND11-L-1LRH3F3]
    steps:
      - uses: actions/checkout@v4
      
      - name: Run some bash commands
        run: |
          mkdir temp
          ls | grep temp
