name: Test actions check
on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Enter the desired runner'
        required: true

jobs:
  build:
    runs-on: 
      - self-hosted
      - ${{ github.event.inputs.runner }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up the runner
        run: echo "Setting up the runner"
      
      - name: Run some bash commands
        run: |
          mkdir temp
