name: Test actions check
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up the runner
        run: echo "Setting up the runner"
      
      - name: Run some bash commands
        run: |
          mkdir temp
