name: "Pull request check and Semantic Update"
on:
  pull_request:
  push:
    branches: [main]
env:
  NODE_VERSION: 20.x
jobs:
  pr-checks:
    name: Validate PR title
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Check the Pull Request title
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            Fix
            Breaking
            Build
            Chore
            Security
            New
            Update
            Upgrade
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
  cypress-run:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    name: Semantic Update
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          persist-credentials: false
     
